import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "secondary": "#75584d",
        "surface": "#fbfbe2",
        "secondary-fixed-dim": "#e4beb2",
        "tertiary-fixed": "#ffe08d",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#88d982",
        "error": "#ba1a1a",
        "on-secondary-container": "#795c51",
        "surface-bright": "#fbfbe2",
        "tertiary-fixed-dim": "#e4c368",
        "surface-variant": "#e4e4cc",
        "on-primary-fixed": "#002204",
        "primary-container": "#2e7d32",
        "outline-variant": "#bfcaba",
        "on-tertiary-fixed-variant": "#584400",
        "on-secondary": "#ffffff",
        "tertiary-container": "#c7a850",
        "tertiary": "#745b04",
        "inverse-on-surface": "#f2f2d9",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1d0e",
        "on-secondary-fixed": "#2b160f",
        "surface-container-highest": "#e4e4cc",
        "surface-dim": "#dbdcc3",
        "inverse-surface": "#303221",
        "surface-container-high": "#eaead1",
        "on-primary": "#ffffff",
        "on-primary-container": "#cbffc2",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#5b4137",
        "surface-container": "#efefd7",
        "surface-tint": "#1b6d24",
        "on-tertiary-fixed": "#241a00",
        "outline": "#707a6c",
        "on-surface-variant": "#40493d",
        "on-tertiary-container": "#4f3d00",
        "on-primary-fixed-variant": "#005312",
        "inverse-primary": "#88d982",
        "primary": "#0d631b",
        "surface-container-low": "#f5f5dc",
        "secondary-fixed": "#ffdbce",
        "on-surface": "#1b1d0e",
        "primary-fixed": "#a3f69c",
        "secondary-container": "#fed7ca",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "playfair": ["Playfair Display", "serif"],
        "poppins": ["Poppins", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ],
};
export default config;
